# -*- coding: utf-8 -*-
"""aula3sub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RszV2hFXV9rKR9wPMja0idx9vrSrSN-X
"""

# ETE PORTO DIGITAL 
# DISCIPLINA: LPC1
# PROFESSOR: CLOVES
# ESTUDANTE: ?

print ('Olá, ETE PORTO DIGITAL!')